name: compile
on: push
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - uses: cachix/install-nix-action@v11
        with:
          skip_adding_nixpkgs_channel: true
      - uses: cachix/cachix-action@v6
        with:
          name: thalesmg
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - name: build
        run: nix-build -A soldo release.nix
